**************model**************
DataParallel(
  (module): pyramid_trans_expr(
    (face_landback): MobileFaceNet(
      (conv1): Conv_block(
        (conv): Conv2d(3, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (prelu): PReLU(num_parameters=64)
      )
      (conv2_dw): Conv_block(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=64, bias=False)
        (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (prelu): PReLU(num_parameters=64)
      )
      (conv_23): Depth_Wise(
        (conv): Conv_block(
          (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=128)
        )
        (conv_dw): Conv_block(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
          (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=128)
        )
        (project): Linear_block(
          (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (conv_3): Residual(
        (model): Sequential(
          (0): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (project): Linear_block(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (1): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (project): Linear_block(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (2): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (project): Linear_block(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (3): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=128)
            )
            (project): Linear_block(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
        )
      )
      (conv_34): Depth_Wise(
        (conv): Conv_block(
          (conv): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=256)
        )
        (conv_dw): Conv_block(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=256, bias=False)
          (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=256)
        )
        (project): Linear_block(
          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (conv_4): Residual(
        (model): Sequential(
          (0): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (1): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (2): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (3): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (4): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (5): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
        )
      )
      (conv_45): Depth_Wise(
        (conv): Conv_block(
          (conv): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=512)
        )
        (conv_dw): Conv_block(
          (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=512, bias=False)
          (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (prelu): PReLU(num_parameters=512)
        )
        (project): Linear_block(
          (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (conv_5): Residual(
        (model): Sequential(
          (0): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (1): Depth_Wise(
            (conv): Conv_block(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (conv_dw): Conv_block(
              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
              (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (prelu): PReLU(num_parameters=256)
            )
            (project): Linear_block(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
        )
      )
      (conv_6_sep): Conv_block(
        (conv): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (prelu): PReLU(num_parameters=512)
      )
      (output_layer): GDC(
        (conv_6_dw): Linear_block(
          (conv): Conv2d(512, 512, kernel_size=(7, 7), stride=(1, 1), groups=512, bias=False)
          (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (conv_6_flatten): Flatten()
        (linear): Linear(in_features=512, out_features=136, bias=False)
        (bn): BatchNorm1d(136, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (ir_back): Backbone(
      (input_layer): Sequential(
        (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): PReLU(num_parameters=64)
      )
      (output_layer): Sequential(
        (0): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): Dropout(p=0.0, inplace=False)
        (2): Flatten()
        (3): Linear(in_features=25088, out_features=512, bias=True)
        (4): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (body): Sequential(
        (0): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=2, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=64)
            (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=64)
            (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (2): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=64)
            (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (3): bottleneck_IR(
          (shortcut_layer): Sequential(
            (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (res_layer): Sequential(
            (0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=128)
            (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (4): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=128)
            (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (5): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=128)
            (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (6): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=128)
            (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (7): bottleneck_IR(
          (shortcut_layer): Sequential(
            (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (res_layer): Sequential(
            (0): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (8): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (9): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (10): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (11): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (12): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (13): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (14): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (15): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (16): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (17): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (18): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (19): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (20): bottleneck_IR(
          (shortcut_layer): MaxPool2d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
          (res_layer): Sequential(
            (0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (2): PReLU(num_parameters=256)
            (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
      )
    )
    (ir_layer): Linear(in_features=1024, out_features=512, bias=True)
    (pyramid_fuse): HyVisionTransformer(
      (pos_drop): Dropout(p=0.0, inplace=False)
      (downsample_m): Conv1d(100, 100, kernel_size=(2,), stride=(2,))
      (downsample_s): Conv1d(100, 100, kernel_size=(4,), stride=(4,))
      (blocks): Sequential(
        (0): PyramidBlock(
          (block_l): Block(
            (drop_path): Identity()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): Identity()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): Identity()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (1): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (2): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (3): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (4): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (5): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (6): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
        (7): PyramidBlock(
          (block_l): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=512, out_features=1024, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=512, out_features=512, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=512, out_features=1024, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=1024, out_features=512, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_m): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=256, out_features=512, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=256, out_features=256, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=256, out_features=512, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=512, out_features=256, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (block_s): Block(
            (drop_path): DropPath()
            (norm1): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_img): Attention_img(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp1): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (norm3): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (attn_lm): Attention_lm(
              (kv): Linear(in_features=128, out_features=256, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=128, out_features=128, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
            )
            (norm4): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
            (mlp2): Mlp(
              (fc1): Linear(in_features=128, out_features=256, bias=True)
              (act): GELU(approximate='none')
              (drop1): Dropout(p=0.0, inplace=False)
              (fc2): Linear(in_features=256, out_features=128, bias=True)
              (drop2): Dropout(p=0.0, inplace=False)
            )
            (conv): Conv1d(100, 100, kernel_size=(1,), stride=(1,))
          )
          (upsample_m): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
          (upsample_s): ConvTranspose1d(100, 100, kernel_size=(2,), stride=(2,))
        )
      )
      (norm): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
    )
    (se_block): SE_block(
      (linear1): Linear(in_features=512, out_features=512, bias=True)
      (relu): ReLU()
      (linear2): Linear(in_features=512, out_features=512, bias=True)
      (sigmod): Sigmoid()
    )
    (head): ClassificationHead(
      (linear): Linear(in_features=512, out_features=7, bias=True)
    )
  )
)